---
- hosts: webservers
  become: yes
  tasks:
  - name: i want to update
    apt:
      update_cache: yes
    when: ansible_os_family == "Debian"
  - name: i want to install webserver
    apt:
     name: apache2
     state: present
    when: ansible_os_family == "Debian"
  - name: i want to update
    apt:
      update_cache: yes
    when: ansible_os_family == "Debian"
  - name: i want to restart the webserver
    service:
      name: apache2
      state: restarted
    when: ansible_os_family == "Debian"
  - name: i want to uninstall the pache2
    apt:
     name: apache2
     autoremove: yes
     state: absent
    when: ansible_os_family == "Debian"
