---
- hosts: webservers
  become: yes
  tasks:
  - name: i want to install java on ubuntu nodes
    apt:
      name: openjdk-8-jdk
      state: present
    when: ansible_os_family == "Debian"
  - name: i want to uninstall java on ubuntu nodes
    apt:
      name:  openjdk-8-jdk
      state: absent
      autoremove: yes
    when: ansible_os_family == "Debian"
  - name: i want to install java on redhat nodes
    yum:
      name: java-1.8.0-openjdk
      state: present
    when: ansible_os_family =="RedHat"
  - name: i want to uninstall java on redhat nodes
    yum: 
      name: java-1.8.0-openjdk
      state: absent
      autoremove: yes
    when: ansible_os_family =="RedHat"