---
- hosts: webservers
  become: yes
  tasks:
  - name: install webservers
    apt:
      name: apache2
      state: present
  - name: copy static file
    copy:
      src: staticfile.html
      dest: /var/www/html/index.html
  - name: copy dynamic file
    template:
      src: index.j2
      dest: /var/www/html/index.html
    notify: restartwebserver
  - name: download jenkins from internet into node
    get_url:
      url: https://get.jenkins.io/war-stable/2.332.3/jenkins.war
      dest: /home/sunitha/
  handlers:
    - name: restartwebserver
      service:
       name: apache2
       state: restarted