---
- hosts: webservers
  become: yes
  tasks:
  - name: install webservers
    apt:
      name: apache2
      state: present
  - name: copy static file
    copy:
      src: staticfile.html
      dest: /var/www/html/index.html