---
- name: download tomcat url
  get_url:
    url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.0/bin/apache-tomcat-10.0.0.tar.gz                                                                                                                                                                                                                                                                                                                             
    dest: /home/sunitha/apache-tomcat-10.0.0.tar.gz
    force_basic_auth: yes 
- name: extract the url
  command:
     cmd: sudo tar xzvf /home/sunitha/apache-tomcat-10.0.0.tar.gz -C /opt/tomcat --strip-components=1
     creates: /opt/tomcat/LICENSE